branches:
 except:
  - /appveyor/

language: perl
perl:
  - "5.24"
  - "5.22"
  - "5.20"
  - "5.18"
  - "5.16"
  - "5.14"
  - "5.12"
  - "5.10"
  - "5.8"
sudo: false
matrix:
  include:
    # The perl does not matter here, system perl will be used
    - perl: "5.18"
      os: osx
      sudo: true
    # Actually the perl here does not matter
    - perl: "5.14"
      env: USE_SYSTEM_PERL=1
      sudo: true
    # Actually the perl here does not matter
    - perl: "5.18"
      env: USE_SYSTEM_PERL=1
      dist: trusty
      sudo: true

before_install:
  - '[ "$USE_SYSTEM_PERL" = 1 ] && (perlbrew off; sudo apt-get update -qq; sudo apt-get install -qq libdatetime-perl) || true'
  - if [ "$TRAVIS_OS_NAME" = "osx" ]; then brew update; brew install cpanminus; fi

install:
  # For system perls, this step shouldn't do anything
  # (all requirements are already met with system packages)
  # On OSX the system perl already comes with DateTime
  - if [ "$USE_SYSTEM_PERL" = "1" -o "$TRAVIS_OS_NAME" = "osx" ]; then cpanm --sudo --quiet --installdeps --notest .; else cpanm --quiet --installdeps --notest .; fi
