language: perl
arch:
  - arm64
matrix:
  include:
    - dist: xenial
      perl: 5.24
    - dist: bionic
      perl: 5.26
    - dist: focal
      perl: 5.32
    - dist: focal
      perl: 5.32
      env: USE_SYSTEM_PERL=1

## perlbrew perls
#    - perl: "5.30"
#      dist: xenial
#    - perl: "5.24"
#      dist: xenial
#    - perl: "5.22"
#      dist: xenial
#    - perl: "5.20"
#      dist: trusty
#    - perl: "5.16"
#      dist: trusty
#    - perl: "5.12"
#      dist: trusty
#    - perl: "5.10"
#      dist: trusty
#    - perl: "5.8"
#      dist: trusty
#
## system perls (perl version does not matter here, only reflects the system perl version (hopefully))
#    - perl: "5.14"
#      env: USE_SYSTEM_PERL=1
#      dist: precise
#      sudo: true
#    - perl: "5.18"
#      env: USE_SYSTEM_PERL=1
#      dist: trusty
#      sudo: true
#    - perl: "5.26"
#      env: USE_SYSTEM_PERL=1
#      dist: xenial
#      sudo: true

## disabled, because too slow
#    - perl: "5.18"
#      os: osx
#      sudo: true

before_install:
  - '[ "$USE_SYSTEM_PERL" = 1 ] && (perlbrew off; sudo apt-get update -qq; sudo apt-get install -qq libdatetime-perl) || true'
  - if [ "$TRAVIS_OS_NAME" = "osx" ]; then brew update; brew install cpanminus; fi

install:
  # For system perls, this step shouldn't do anything
  # (all requirements are already met with system packages)
  # On OSX the system perl already comes with DateTime
  - if [ "$USE_SYSTEM_PERL" = "1" -o "$TRAVIS_OS_NAME" = "osx" ]; then cpanm --sudo --quiet --installdeps --notest .; else cpanm --quiet --installdeps --notest .; fi

branches:
 except:
  - /appveyor/
sudo: false
